sunshine:
  image:
    repository: ghcr.io/games-on-whales/sunshine
    tag: 1.0.0
    pullPolicy: IfNotPresent
  user: admin
  password: admin
  logLevel: info
  env: {}
xorg:
  image:
    repository: ghcr.io/games-on-whales/xorg
    tag: 1.0.0
    pullPolicy: IfNotPresent
  display: :99
  refreshrate: 60
  resolution: 1920x1080
pulseaudio:
  image:
    repository: ghcr.io/games-on-whales/pulseaudio
    tag: 1.0.0
    pullPolicy: IfNotPresent
retroarch:
  enabled: true
  image:
    repository: ghcr.io/games-on-whales/retroarch
    tag: 1.0.0
    pullPolicy: IfNotPresent
  logLevel: info
  volumeMounts: []
steam:
  enabled: true
  image:
    repository: ghcr.io/games-on-whales/steam
    tag: 1.0.0
    pullPolicy: IfNotPresent
  protonLog: 1
  volumeMounts: []
mkhomeretrodirs:
  image:
    repository: busybox
    tag: 1.34.0
    pullPolicy: IfNotPresent

persistence:
  config:
    enabled: true
    mountPath: "/gow"
  games:
    enabled: true
    mountPath: "/games"
service:
    main: {}
    udp: {}
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
# workload:
#   main:
#     podSpec:
#       containers:
#         main:
#           probes:
#             liveness:
#               enabled: false
#             readiness:
#               enabled: false
#             startup:
#               enabled: false
#           env:

